Migrate Imagination gpu 1.18 kernel module from linux 5.17 to 6.6
eswincomputing/linux-stable pull request #1
Opened 2024-07-09 09:26 UTC by Sakura286

Migrate Imagination gpu 1.18 kernel module from linux 5.17 to 6.6

Some changes are quite rough. Need someone help to review.

orig: https://github.com/RevySR/linux-eswin/pull/1

2024-07-10 01:50 UTC, linmineswincomputing requested changes
Do not change sifive_ccache.c,. Using arch_sync_dma_for_device/cpu instead of sifive_l2_flush64_range in  sysconfig.c

2024-07-10 02:08 UTC, linmineswincomputing requested changes
#include <linux/dma-map-ops.h> to use arch_sync_dma_for_cpu/device

2024-07-10 02:24 UTC, linmineswincomputing commented
It would be better to combine these commits into one commit, since these commits are the  same topic. It will make the kernel commit history more clean.

2024-07-10 02:30 UTC, linmineswincomputing commented on drivers/soc/sifive/sifive_ccache.c
Do not change sifive_ccace.c. Other drivers shhould  use arch_sync_dma_for_device/cpu.

2024-07-10 07:13 UTC, Sakura286 commented
> It would be better to combine these commits into one commit, since these commits are the same topic. It will make the kernel commit history more clean.

Splitting the commits will be more friendly for reviewer. It seems that the reviewer can squash or rebase multiple commits?

![2024-07-10 15 12 27](https://github.com/eswincomputing/linux-stable/assets/22614226/54454a75-055e-4006-ad49-fe1861c81c01)

2024-07-10 10:58 UTC, Sakura286 commented on drivers/soc/sifive/sifive_ccache.c
Fixed. Please see https://github.com/eswincomputing/linux-stable/pull/1/commits/8b82c25c272d2ca026427c89afa83c9021af74d4

2024-07-11 02:08 UTC, linmineswincomputing approved these changes

2024-07-11 02:08 UTC, linmineswincomputing commented on include/soc/sifive/sifive_ccache.h
Do not change sifive_ccace.h. Other drivers shhould use arch_sync_dma_for_device/cpu

2024-07-15 07:25 UTC, closed without merging